---
    - name: Register the system
      community.general.redhat_subscription:
       username: "{{ username }}"
       password: "{{ password }}"
    - name: Login to quay
      containers.podman.podman_login:
       username: "{{ registryusername }}"
       password: "{{ registrypassword }}"
       registry: registry.redhat.io
    - name: configuring firewall
      ansible.posix.firewalld:
        port: "{{ item }}"
        permanent: yes
        state: enabled
        immediate: true
      loop:
        - 80/tcp
        - 443/tcp
        - 5432/tcp
        - 5433/tcp
        - 6379/tcp
    - name: Reload Firewalld
      systemd:
         name: firewalld
         state: reloaded
    - name: Make an /etc/hosts entry
      ansible.builtin.lineinfile:
       path: /etc/hosts
       line: "{{ ansible_default_ipv4.address }} {{ ansible_fqdn }}"
       state: present
    - name: Remove containers if they exist
      containers.podman.podman_container:
       name: "{{ item }}"
       state: absent
      loop:
         - quay
         - postgresql-quay
         - redis
    - name: Configure Database directory
      ansible.builtin.shell:
        cmd: |
         mkdir -p $QUAY/postgres-quay
         setfacl -m u:26:-wx $QUAY/postgres-quay
    - name: Starting the postgresql-quay container
      containers.podman.podman_container:
        name: postgresql-quay
        image: registry.redhat.io/rhel8/postgresql-13:1-109
        env:
          POSTGRESQL_USER: "quayuser"
          POSTGRESQL_PASSWORD: "quaypass"
          POSTGRESQL_DATABASE: "quay"
          POSTGRESQL_ADMIN_PASSWORD: "adminpass"
        ports:
          - "5432:5432"
        volumes:
          - /postgres-quay:/var/lib/pgsql/data:Z
        state: started
    - name: Creating pg_trgm extension
      ansible.builtin.shell:
       cmd: |
        podman exec -it postgresql-quay /bin/bash -c 'echo "CREATE EXTENSION IF NOT EXISTS pg_trgm" | psql -d quay -U postgres'
    - name: Starting the redis container
      containers.podman.podman_container:
        name: redis
        image: registry.redhat.io/rhel8/redis-6:1-110
        env:
          REDIS_PASSWORD: "strongpassword"
        ports:
          - "6379:6379"
        state: started
    - name: Creating quay container configuration
      ansible.builtin.shell:
        cmd: |
          mkdir $QUAY/config
          mkdir $QUAY/storage
          setfacl -m u:1001:-wx $QUAY/storage
    - name: Copying the config.yaml file
      ansible.builtin.copy:
        src: config
        dest: /config/config.yaml
        mode: '0644'
    - name: Starting the postgresql-quay container
      containers.podman.podman_container:
        name: quay
        image: registry.redhat.io/quay/quay-rhel8:v3.10.5
        ports:
          - "80:8080"
          - "443:8443"
        volumes:
          - /config:/conf/stack:Z
          - /storage:/datastorage:Z
        state: started
    - name: Print message login and configure quay
      ansible.builtin.debug:
        msg: "QUAY is installed and configured, you can login to quay by browsing the http://{{ ansible_fqdn }}"
